{{- if and (eq .Values.addons.minioOperator.sourceType "git") (not .Values.offline) (or .Values.addons.minioOperator.enabled .Values.addons.minio.enabled (and .Values.addons.thanos.enabled (.Values.addons.thanos.values.objstoreConfig | empty) (.Values.addons.thanos.objectStorage.endpoint | empty))) }}
{{- $gitCredsDict := dict
  "name" "minioOperator"
  "packageGitScope" .Values.addons.minioOperator.git
  "rootScope" .
  "releaseName" .Release.Name
}}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minio-operator
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.minioOperator.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.minioOperator.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCredsExtended" $gitCredsDict | nindent 2 }}
{{- end }}
