{{- if and (eq .Values.addons.headlamp.sourceType "git") .Values.addons.headlamp.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "headlamp" "gitCredsName" "headlamp" "git" .Values.addons.headlamp.git "component" "core" "root" .) }}
{{- end }}
