{{- if .Values.addons.headlamp.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.headlamp "name" "headlamp" "defaults" (include "bigbang.defaults.headlamp" .)) }}
{{- end }}

{{- define "bigbang.defaults.headlamp" -}}

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

{{- if .Values.istio.enabled }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

istio:
  enabled: {{ .Values.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.addons.headlamp.values)
      (dig "hardened" "enabled" false .Values.istio.values)
    }}

openshift: {{ .Values.openshift }}
{{- end -}}
