{{- if .Values.addons.anchoreEnterprise.enabled }}
{{- /* Create a cleaned copy of anchore config and merge deprecated paths into current paths */ -}}
{{- $anchorePackage := deepCopy .Values.addons.anchoreEnterprise -}}
{{- if .Values.addons.anchoreEnterprise.values -}}
{{- $cleanedValues := include "mergeLegacyIstioHardenedKeys" (dict "values" .Values.addons.anchoreEnterprise.values) | fromYaml -}}
{{- $anchorePackage = set $anchorePackage "values" $cleanedValues -}}
{{- end -}}
{{- include "values-secret" (dict "root" $ "package" $anchorePackage "name" "anchore-enterprise" "defaults" (include "bigbang.defaults.anchoreEnterprise" .)) }}
{{- end }}

{{- define "bigbang.defaults.anchoreEnterprise" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- $istioHardenedEnabled := or (dig "istio" "hardened" "enabled" false .Values.addons.anchoreEnterprise.values) (dig "hardened" "enabled" false .Values.istiod.values) }}
{{- $externalRedisEnabled := and .Values.addons.anchoreEnterprise.redis.host .Values.addons.anchoreEnterprise.redis.port .Values.addons.anchoreEnterprise.redis.password }}
{{- $externalPostgresEnabled := and .Values.addons.anchoreEnterprise.database.host .Values.addons.anchoreEnterprise.database.port .Values.addons.anchoreEnterprise.database.username .Values.addons.anchoreEnterprise.database.password .Values.addons.anchoreEnterprise.database.database }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
  {{- if and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.addons.anchoreEnterprise) "enabled") }}
  {{- if (eq (dig "values" "istio" "mtls" "mode" "STRICT" .Values.addons.anchoreEnterprise) "STRICT") }}
  serviceMonitor:
    scheme: "https"
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true
  {{- end }}
  {{- end }}

routes:
  inbound:
    api:
      enabled: true
      gateways:
        - {{ include "getGatewayName" (dict "gateway" .Values.addons.anchoreEnterprise.ingress.gateway "root" .)}}
      hosts:
        - anchore-api.{{ $domainName }}
      service: anchore-enterprise-anchore-enterprise-api.anchore.svc.cluster.local
      port: 8228
    ui:
      enabled: true
      gateways:
        - {{ include "getGatewayName" (dict "gateway" .Values.addons.anchoreEnterprise.ingress.gateway "root" .)}}
      hosts:
        - anchore.{{ $domainName }}
      service: anchore-enterprise-anchore-enterprise-ui.anchore.svc.cluster.local
      port: 3000
  outbound:
    anchore-data-service:
      enabled: true
      hosts:
      - data.anchore-enterprise.com
    bb-tests:
      enabled: {{ dig "bbtests" "enabled" false .Values.addons.anchoreEnterprise.values }}
      hosts:
      - 'repo1.dso.mil'
      - 'auth.docker.io'
      - 'registry-1.docker.io'

istio:
  enabled: {{ $istioEnabled }}
  hardened:
    enabled: {{ $istioHardenedEnabled }}

  sidecar:
    enabled: {{ $istioHardenedEnabled }}

  authorizationPolicies:
    enabled: {{ $istioHardenedEnabled }}
    generateFromNetpol: true

networkPolicies:
  enabled: false
  # note: ztunnel does not exist yet, defaulting to false until ambient package is added
  hbonePortInjection:
    enabled: {{ dig "enabled" false (default dict .Values.ztunnel) }}
  ingress:
    definitions: 
      {{ toYaml .Values.networkPolicies.ingress.definitions | nindent 6 }}
    to:
      catalog:8082:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: catalog
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      simplequeue:8083:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: simplequeue
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      analyzer:8084:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: analyzer
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      policy:8087:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: policyengine
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      api:8228:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: api
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      reports:8558:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: reports
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      notifications:8668:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: notifications
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
      ui-redis:9121:
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: {{ .Values.monitoring.enabled }}
  egress:
    definitions:
      {{ toYaml .Values.networkPolicies.egress.definitions | nindent 6 }}
    from:
      "*":
        to:
          k8s:
            tempo/tempo:9411: {{ .Values.tempo.enabled }}
      api:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: api
        to:
          definition:
            redis-subnets: {{ $externalRedisEnabled }}
            database-subnets: {{ $externalPostgresEnabled }}
      catalog:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: catalog
        to:
          definition:
            database-subnets: {{ $externalPostgresEnabled }}
      datasyncer:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: datasyncer
        to:
          definition:
            anchore-data-service: true
            external-data-service: false # can we use some logic here
            database-subnets: {{ $externalPostgresEnabled }}
      notifications:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: notifications
        to:
          definition:
            notification-services: true
      simplequeue:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: simplequeue
        to:
          definition:
            database-subnets: {{ $externalPostgresEnabled }}
      ui:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: ui
        to:
          definition:
            ldap-subnets: false
            redis-subnets: {{ $externalRedisEnabled }}
            database-subnets: {{ $externalPostgresEnabled }}
      upgrade:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: upgradejob
        to:
          definition:
            database-subnets: {{ $externalPostgresEnabled }}
  additionalPolicies: []

sso:
  enabled: {{ .Values.addons.anchoreEnterprise.sso.enabled }}
  spEntityId: {{ .Values.addons.anchoreEnterprise.sso.client_id }}
  {{- $anchoreUrl := first (dig "istio" "ui" "hosts" list .Values.addons.anchoreEnterprise.values) }}
  acsUrl: https://{{ tpl ($anchoreUrl | default (printf "%s.%s" "anchore" $domainName)) . }}/service/sso/auth/keycloak
  idpMetadataUrl: "{{ include "sso.saml.descriptor" . }}"
  roleAttribute: {{ .Values.addons.anchoreEnterprise.sso.role_attribute }}

global:
  imagePullSecretName: private-registry

imagePullPolicy: {{ .Values.imagePullPolicy }}

postgresql:
  {{- if $istioEnabled }}
  podAnnotations:
    {{ include "istioAnnotation" . }}
  {{- end}}
  imagePullSecrets: private-registry
  {{- if $externalPostgresEnabled }}
  enabled: false
  postgresUser: {{ .Values.addons.anchoreEnterprise.database.username }}
  postgresPassword: {{ .Values.addons.anchoreEnterprise.database.password }}
  postgresDatabase: {{ .Values.addons.anchoreEnterprise.database.database }}
  externalEndpoint: "{{ .Values.addons.anchoreEnterprise.database.host }}"
  postgresPort: {{ .Values.addons.anchoreEnterprise.database.port }}
  {{- end }}

upstream:
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  {{- if .Values.addons.anchoreEnterprise.enterprise.licenseYaml }}
  license: 
    {{- .Values.addons.anchoreEnterprise.enterprise.licenseYaml | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.addons.anchoreEnterprise.adminPassword }}
  anchoreConfig:
    default_admin_password: {{ .Values.addons.anchoreEnterprise.adminPassword }}
  {{- end }}
  feeds:
    istio:
      enabled: {{ $istioEnabled }}
      injection: {{ ternary "enabled" "disabled" (and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.addons.anchoreEnterprise) "enabled")) }}

  postgresql:
    {{- if $istioEnabled }}
    podAnnotations:
      {{ include "istioAnnotation" . }}
    {{- end}}
    imagePullSecrets: private-registry
    {{- if $externalPostgresEnabled }}
    auth:
      username: {{ .Values.addons.anchoreEnterprise.database.username }}
      password: {{ .Values.addons.anchoreEnterprise.database.password }}
      database: {{ .Values.addons.anchoreEnterprise.database.database }}
    externalEndpoint: "{{ .Values.addons.anchoreEnterprise.database.host }}"
    primary:
      service:
        ports:
          postgresql: {{ .Values.addons.anchoreEnterprise.database.port }}
    {{- end }}

  ui:
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    imagePullSecretName: private-registry

ui-redis:
  {{- if $externalRedisEnabled }}
  # We are using an external redis url
  externalEndpoint: "redis://{{ .Values.addons.anchoreEnterprise.redis.username | default "nouser" }}:{{ .Values.addons.anchoreEnterprise.redis.password }}@{{ .Values.addons.anchoreEnterprise.redis.host }}:{{ .Values.addons.anchoreEnterprise.redis.port }}"
  upstream:
    enabled: false
  {{- else }}
  # We are using an internal,dev redis url
  upstream:
    {{- if $istioEnabled }}
    master:
      podAnnotations:
        {{ include "istioAnnotation" . }}
    replica:
      podAnnotations:
        {{ include "istioAnnotation" . }}
    {{- end }}
    image:
      pullSecrets:
        - private-registry
    {{- if .Values.monitoring.enabled }}
    metrics:
      enabled: true
      image:
        pullSecrets:
          - private-registry
      serviceMonitor:
        enabled: true
        namespace: anchore
        selector:
          app.kubernetes.io/name: ui-redis
          app.kubernetes.io/instance: anchore-enterprise
        {{- if and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.addons.anchoreEnterprise) "enabled") }}
        {{- if (eq (dig "values" "istio" "mtls" "mode" "STRICT" .Values.addons.anchoreEnterprise) "STRICT") }}
        scheme: "https"
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          keyFile: /etc/prom-certs/key.pem
          insecureSkipVerify: true
        {{- end }}
        {{- end }}
      prometheusRule:
        enabled: true
        namespace: monitoring
    {{- end }}
  {{- end }}




{{- end }}
