{{- $gitCredsSecretDict := dict
  "name" "renovate"
  "targetScope" .Values.addons.renovate
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
