{{- if and (eq .Values.addons.backstage.sourceType "git") .Values.addons.backstage.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "backstage" "gitCredsName" "backstage" "git" .Values.addons.backstage.git "component" "developer-tools" "root" .) }}
{{- end }}
