{{- if and (eq .Values.addons.velero.sourceType "git") .Values.addons.velero.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "velero" "gitCredsName" "velero" "git" .Values.addons.velero.git "component" "cluster-utilities" "root" .) }}
{{- end }}
