{{- /* Used for creating namespaces that package's use. */ -}}
{{- /* If two packages reside in the same namespace, set namespace.create=false in one of them. */ -}}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) (dig "namespace" "create" true $vals) -}}
{{- $pkg = include "resourceName" $pkg -}}
{{- /* BB Maintained: Auto-enable istio injection when flag is true and istiod is enabled */ -}}
{{- $bbMaintained := dig "bb_maintained" false $vals -}}
{{- $istioInjection := dig "istio" "injection" "enabled" $vals -}}
{{- if and $bbMaintained $istioEnabled (not (dig "istio" "injection" nil $vals)) -}}
{{- $istioInjection = "enabled" -}}
{{- end -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" $ | nindent 4 }}
    {{- if $istioEnabled }}
    istio-injection: {{ tpl $istioInjection $ }}
    {{- end }}
    {{- if (dig "namespace" "labels" nil $vals) -}}
    {{- toYaml $vals.namespace.labels | nindent 4 -}}
    {{- end -}}
  {{- if (dig "namespace" "annotations" nil $vals) }}
  annotations:
    {{- toYaml $vals.namespace.annotations | nindent 4 -}}
  {{- end }}
---
{{ end -}}
{{- end -}}