{{- if and .Values.istio3.enabled ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: istio-gateway
  labels:
    app.kubernetes.io/name: istio-gateway
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
