{{- if .Values.istioGateway.enabled }}
{{- range $name, $values := .Values.istioGateway.gateways }}
{{- if $values.servers }}
{{- range $index, $servervalues := $values.servers }}
{{- if and (dig "tls" "cert" "" $servervalues) (dig "tls" "key" "" $servervalues) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%d-%s-cert" $index $name }}
  namespace: istio-ingress
  labels:
    app.kubernetes.io/name: istio-gateway
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
type: kubernetes.io/tls
data:
  tls.crt: {{ $servervalues.tls.cert | b64enc }}
  tls.key: {{ $servervalues.tls.key | b64enc }}
  {{- if $servervalues.tls.ca }}
  ca.crt: {{ $servervalues.tls.ca | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
