{{- if and (eq .Values.kyvernoPolicies.sourceType "git") .Values.kyvernoPolicies.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "kyverno-policies" "gitCredsName" "kyvernoPolicies" "git" .Values.kyvernoPolicies.git "root" .) }}
{{- end }}
