{{- $defaults := fromYaml (include "bigbang.defaults.kyverno-policies" .root) -}}
{{- $overrides := .Values.kyvernoPolicies -}}

#{{- include "bigbang.overlays.kyverno-policies" (dict
#  "Values" (dict "kyvernoPolicies" $overrides)
#  "Template" "test"
#  "Release" .Release
#  "Chart" .Chart
#  "Capabilities" .Capabilities
#  "Files" .Files
#  "Values" (merge $defaults (dict "kyvernoPolicies" $overrides))
#) }}

{{- include "bigbang.overlays.kyverno-policies" . }}