{{- if and (eq .Values.addons.externalSecrets.sourceType "git") .Values.addons.externalSecrets.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "external-secrets" "gitCredsName" "externalSecrets" "git" .Values.addons.externalSecrets.git "component" "core" "root" .) }}
{{- end }}
